python/projects/Django_Transportation_Management_System-main/PPWuLiu/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', RedirectView.as_view(url='tms/login')),
    path('tms/', include('wuliu.urls')),
    path('utils/', include('utils.urls')),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

python/projects/Django_Transportation_Management_System-main/utils/urls.py
from django.urls import path

from . import views

app_name = "utils"
urlpatterns = [
    path("export_excel", views.export_excel, name="export_excel"),
]

python/projects/Django_Transportation_Management_System-main/wuliu/urls.py
from django.urls import path, include

from . import views, apis

# Unused
def easy_path(view_func):
    """ 只需给定视图函数, route和name都设置为视图函数的名字 """
    return path(view_func.__name__, view_func, name=view_func.__name__)

app_name = "wuliu"
urlpatterns = [
    # 登录
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("change_password", views.change_password, name="change_password"),
    path("", views.welcome, name="welcome"),
    path("welcome_action.js", views.welcome_js, name="welcome_js"),
    # 系统设置
    path("settings/", include([
        path("manage_users", views.manage_users, name="manage_users"),
        path("add_user", views.add_user, name="add_user"),
        path("manage_user_permission", views.manage_user_permission, name="manage_user_permission"),
        path("batch_edit_user_permission", views.batch_edit_user_permission, name="batch_edit_user_permission"),
    ])),
    # 运单管理
    path("waybill/", include([
        path("add", views.add_waybill, name="add_waybill"),
        path("edit", views.edit_waybill, name="edit_waybill"),
        path("edit.js", views.edit_waybill_js, name="edit_waybill_js"),
        path("manage", views.ManageWaybill.as_view(), name="manage_waybill"),
        path("manage.js", views.manage_waybill_js, name="manage_waybill_js"),
        path("detail/<int:waybill_id>", views.detail_waybill, name="detail_waybill"),
        path("quick_search", views.quick_search_waybill, name="quick_search_waybill"),
        path("confirm_return", views.confirm_return_waybill, name="confirm_return_waybill"),
    ])),
    # 发车管理
    path("transport_out/", include([
        path("add", views.add_transport_out, name="add_transport_out"),
        path("edit", views.edit_transport_out, name="edit_transport_out"),
        path("edit.js", views.edit_transport_out_js, name="edit_transport_out_js"),
        path("manage", views.manage_transport_out, name="manage_transport_out"),
        path("manage.js", views.manage_transport_out_js, name="manage_transport_out_js"),
        path("detail", views.detail_transport_out, name="detail_transport_out"),
        path("search_waybills", views.SearchWaybillsToTransportOut.as_view(), name="search_waybills_to_transport_out"),
        path("add_waybills", views.add_waybills_to_transport_out, name="add_waybills_to_transport_out"),
    ])),
    # 到货管理
    path("arrival/", include([
        path("manage", views.manage_arrival, name="manage_arrival"),
        path("confirm", views.confirm_arrival, name="confirm_arrival"),
    ])),
    # 客户签收
    path("sign_for/", include([
        path("manage", views.ManageSignFor.as_view(), name="manage_sign_for"),
        path("confirm", views.confirm_sign_for, name="confirm_sign_for"),
        path("confirm.js", views.confirm_sign_for_js, name="confirm_sign_for_js"),
    ])),
    # 财务管理
    path("finance/", include([
        path("department_payment/", include([
            path("add", views.add_department_payment, name="add_department_payment"),
            path("manage", views.manage_department_payment, name="manage_department_payment"),
            path("manage.js", views.manage_department_payment_js, name="manage_department_payment_js"),
            path("detail/<int:dp_id>", views.detail_department_payment, name="detail_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("add", views.add_cargo_price_payment, name="add_cargo_price_payment"),
            path("edit", views.edit_cargo_price_payment, name="edit_cargo_price_payment"),
            path("edit.js", views.edit_cargo_price_payment_js, name="edit_cargo_price_payment_js"),
            path("detail/<int:cpp_id>", views.detail_cargo_price_payment, name="detail_cargo_price_payment"),
            path("manage", views.manage_cargo_price_payment, name="manage_cargo_price_payment"),
            path("manage.js", views.manage_cargo_price_payment_js, name="manage_cargo_price_payment_js"),
        ])),
        path("customer_score_log/", include([
            path("manage", views.manage_customer_score, name="manage_customer_score"),
            path("add", views.add_customer_score_log, name="add_customer_score_log"),
        ])),
    ])),
    # 业务报表
    path("report_table/", include([
        path("src_waybill", views.ReportTableSrcWaybill.as_view(), name="report_table_src_waybill"),
        path("stock_waybill", views.ReportTableStockWaybill.as_view(), name="report_table_stock_waybill"),
        path("dst_waybill", views.ReportTableDstWaybill.as_view(), name="report_table_dst_waybill"),
        path("dst_stock_waybill", views.ReportTableDstStockWaybill.as_view(), name="report_table_dst_stock_waybill"),
        path("sign_for_waybill", views.ReportTableSignForWaybill.as_view(), name="report_table_sign_for_waybill"),
    ])),
    # apis
    path("api/", include([
        path("gen_standard_fee", apis.gen_standard_fee, name="api_gen_standard_fee"),
        path("check_old_password", apis.check_old_password, name="api_check_old_password"),
        # 用以获取模型对象属性的api
        path("get/", include([
            path("customer_info", apis.get_customer_info, name="api_get_customer_info"),
            path("department_info", apis.get_department_info, name="api_get_department_info"),
            path("waybills_info", apis.get_waybills_info, name="api_get_waybills_info"),
            path("truck_info", apis.get_truck_info, name="api_get_truck_info"),
            path("user_info", apis.get_user_info, name="api_get_user_info"),
            path("user_permission", apis.get_user_permission, name="api_get_user_permission"),
        ])),
        # 用以操作模型和会话的api
        path("remove_waybill_when_add_transport_out", apis.remove_waybill_when_add_transport_out,
             name="api_remove_waybill_when_add_transport_out"),
        path("remove_waybill_when_edit_transport_out", apis.remove_waybill_when_edit_transport_out,
             name="api_remove_waybill_when_edit_transport_out"),
        path("add_waybill_when_confirm_sign_for", apis.add_waybill_when_confirm_sign_for,
             name="api_add_waybill_when_confirm_sign_for"),
        path("add_waybill_when_edit_cargo_price_payment", apis.add_waybill_when_edit_cargo_price_payment,
             name="api_add_waybill_when_edit_cargo_price_payment"),
        path("drop_waybill", apis.DropWaybill.as_view(), name="api_drop_waybill"),
        path("drop_transport_out", apis.DropTransportOut.as_view(), name="api_drop_transport_out"),
        path("start_transport_out", apis.StartTransportOut.as_view(), name="api_start_transport_out"),
        path("confirm_arrival", apis.ConfirmArrival.as_view(), name="api_confirm_arrival"),
        path("confirm_sign_for", apis.ConfirmSignFor.as_view(), name="api_confirm_sign_for"),
        path("department_payment/", include([
            path("modify_remark", apis.ModifyRemarkDepartmentPayment.as_view(),
                 name="api_modify_remark_department_payment"),
            path("drop", apis.DropDepartmentPayment.as_view(),
                 name="api_drop_department_payment"),
            path("review", apis.ConfirmReviewDepartmentPayment.as_view(),
                 name="api_review_department_payment"),
            path("pay", apis.ConfirmPayDepartmentPayment.as_view(),
                 name="api_pay_department_payment"),
            path("settle_accounts", apis.ConfirmSettleAccountsDepartmentPayment.as_view(),
                 name="api_settle_accounts_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("drop", apis.DropCargoPricePayment.as_view(),
                 name="api_drop_cargo_price_payment"),
            path("submit", apis.ConfirmSubmitCargoPricePayment.as_view(),
                 name="api_submit_cargo_price_payment"),
            path("review", apis.ConfirmReviewCargoPricePayment.as_view(),
                 name="api_review_cargo_price_payment"),
            path("reject", apis.ConfirmRejectCargoPricePayment.as_view(),
                 name="api_reject_cargo_price_payment"),
            path("pay", apis.ConfirmPayCargoPricePayment.as_view(),
                 name="api_pay_cargo_price_payment"),
        ])),
    ])),
]

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/waybill/_layout_edit_waybill.html
{% extends "wuliu/_layout.html" %}
{% load wuliu_extras %}
{% block head_append_js %}
  <script src="{% url 'wuliu:edit_waybill_js' %}"></script>
{% endblock %}
          {% block content %}
              {% block content_header %}{% endblock %}
            <form action="{% block edit_form_action %}{% endblock %}" id="form-edit_waybill" class="form col-12" method="post">
                <fieldset>
                  {# 为了安全起见, 运单详情页面不提供csrf_token #}
                  {% if not detail_view %}
                    {% csrf_token %}
                  {% endif %}
                    <legend class="row">基本信息</legend>
                  {% if form.id_ %}
                    <div class="row">
                        {% show_form_input_field form.id_ "" "col-6 col-md-3" %}
                        {% show_form_input_field form.id "" "" %}
                      {% if detail_view %}
                        {% show_form_input_field form.create_time "" "col-6 col-md-3" %}
                        {% show_form_input_field form.status "" "col-6 col-md-2" %}
                      {% endif %}
                    </div>
                  {% endif %}
                    <div class="row mb-2">
                        {% show_form_input_field form.src_department "" "col-6 col-md-3" %}
                        {% show_form_input_field form.dst_department "" "col-6 col-md-3" %}
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6"><div class="callout callout-info shadow">
                            <div class="row mb-2">
                                <h3 class="card-title"><i class="fas fa-map-marker-alt mr-2"></i>发货人信息</h3>
                            </div>
                            <div class="row">
                                {% show_form_input_field form.src_customer "选择客户" "col-12" %}
                                {% show_form_input_field form.src_customer_name "姓名" "col-5" %}
                                {% show_form_input_field form.src_customer_phone "电话" "col-7" %}
                                {% show_form_input_field form.src_customer_credential_num "身份证号码" "col-md-5" %}
                                {% show_form_input_field form.src_customer_address "详细地址" "col-md-7" %}
                            </div>
                        </div></div>
                        <div class="col-12 col-md-6"><div class="callout callout-success shadow">
                            <div class="row mb-2">
                                <h3 class="card-title"><i class="fas fa-map-marker-alt mr-2"></i>收货人信息</h3>
                            </div>
                            <div class="row">
                                {% show_form_input_field form.dst_customer "选择客户" "col-12" %}
                                {% show_form_input_field form.dst_customer_name "姓名" "col-5" %}
                                {% show_form_input_field form.dst_customer_phone "电话" "col-7" %}
                                {% show_form_input_field form.dst_customer_credential_num "身份证号码" "col-md-5" %}
                                {% show_form_input_field form.dst_customer_address "详细地址" "col-md-7" %}
                            </div>
                        </div></div>
                    </div>
                    <legend class="row">货物信息</legend>
                    <div class="row">
                        {% show_form_input_field form.cargo_name "" "col-4 col-md" %}
                        {% show_form_input_field form.cargo_num "" "col-4 col-md" %}
                        {% show_form_input_field form.cargo_volume "总体积 (m³)" "col-4 col-md" %}
                        {% show_form_input_field form.cargo_weight "总重量 (Kg)" "col-4 col-md" %}
                        {% show_form_input_field form.cargo_price "货款 (元)" "col-4 col-md" %}
                        {% show_form_input_field form.cargo_handling_fee "手续费 (元)" "col-4 col-md" %}
                    </div>
                    <legend class="row">运费</legend>
                  {# 运单详情页面不显示标准运费 #}
                  {% if not detail_view %}
                    <div class="row">
                        <span class="ml-2 my-1">标准运费：<code id="_fee_standard">0</code>元</span>
                    </div>
                  {% endif %}
                    <div class="row">
                        {% show_form_input_field form.fee "运费 (元)" "col-6 col-md-2" %}
                        {% show_form_input_field form.fee_type "支付方式" "col-6 col-md-2" %}
                        {% show_form_input_field form.customer_remark "" %}
                        {% show_form_input_field form.company_remark "" %}
                    </div>
                    <div class="row">
                        <div class="col-6 col-sm-4 col-md-2">
                            <p>
                                <b>现付合计：</b>
                                <span class="total-fee"><span id="_fee_now">0</span></span>
                            </p>
                        </div>
                        <div class="col-6 col-sm-4 col-md-3">
                            <p>
                                <b>提货应付：</b>
                                <span class="total-fee"><span id="_fee_dst">0</span></span>
                            </p>
                        </div>
                    </div>
                  {# 运单详情页面不提供提交按钮 #}
                  {% if not detail_view %}
                    <button type="submit" class="btn btn-primary">提交</button>
                  {% endif %}
                </fieldset>
            </form>
              {% block content_footer %}{% endblock %}
          {% endblock %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/waybill/add_waybill.html
{% extends "wuliu/waybill/_layout_edit_waybill.html" %}
{% block title %}运单录入{% endblock %}
{% block header_title %}运单录入{% endblock %}
{% block header_subtitle %}收货开票{% endblock %}
{% block edit_form_action %}{% url 'wuliu:add_waybill' %}{% endblock %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/waybill/confirm_return_waybill.html
{% extends "wuliu/_layout.html" %}
{% block title %}确认退货{% endblock %}
{% block header_title %}确认退货{% endblock %}
          {% block content %}
            <div class="accordion col-12">
                <div class="card bg-light shadow">
                    <div class="card-header">
                        <h3 class="card-title">运单编号：{{ waybill.get_full_id }}</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                发货人：<code>{{ waybill.src_customer_name }}</code>
                            </div>
                            <div class="col-md-3">
                                发货人电话：<code>{{ waybill.src_customer_phone }}</code>
                            </div>
                            <div class="col-md-3">
                                收货人：<code>{{ waybill.dst_customer_name }}</code>
                            </div>
                            <div class="col-md-3">
                                收货人电话：<code>{{ waybill.dst_customer_phone }}</code>
                            </div>
                            <div class="col-md-3">
                                发货部门：<code>{{ waybill.src_department.name }}</code>
                            </div>
                            <div class="col-md-3">
                                货物名称：<code>{{ waybill.cargo_name }}</code>
                            </div>
                            <div class="col-md-3">
                                代收货款：<code>{{ waybill.cargo_price }}</code>
                            </div>
                            <div class="col-md-3">
                                件数：<code>{{ waybill.cargo_num }}</code>
                            </div>
                            <div class="col-md-3">
                                总体积：<code>{{ waybill.cargo_volume | floatformat:2 }}</code>
                            </div>
                            <div class="col-md-3">
                                总重量：<code>{{ waybill.cargo_weight | floatformat }}</code>
                            </div>
                            <div class="col-md-3">
                                运费：<code>{{ waybill.fee }}</code>
                            </div>
                            <div class="col-md-3">
                                结算方式：<code>{{ waybill.fee_type }}</code>
                            </div>
                            <div class="col-md-6">
                                客户备注：<code>{{ waybill.customer_remark | default:"无" }}</code>
                            </div>
                            <div class="col-md-6">
                                公司备注：<code>{{ waybill.company_remark | default:"无" }}</code>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <form id="form-confirm_return_waybill" action="{% url 'wuliu:confirm_return_waybill' %}" class="form col-12" method="post">
                {% csrf_token %}
                <input type="number" name="return_waybill_id" value="{{ waybill.id }}" hidden required/>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label label-required">请输入退货原因：</label>
                    <div class="col-md-8">
                        <input class="form-control" type="text" name="return_reason" required/>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-primary" id="confirm_return_waybill_submit">确认退货</button>
                    </div>
                </div>
            </form>
            <script>
$(document).ready(function() {
  $("#confirm_return_waybill_submit").click(function(e) {
    e.preventDefault();
    if (! $('#form-confirm_return_waybill [name="return_waybill_id"]').val()) {
      mdtoast_error("表单异常！请刷新页面后重新提交！");
      return;
    }
    if (! $('#form-confirm_return_waybill [name="return_reason"]').val().trim()) {
      mdtoast_error("请仔细填写退货原因！");
      return;
    }
    confirm_dialog(
      "确认退货", "退货操作无法撤销！你确定要退货吗？", {
        okClick: function() {
          this.hide();
          $('#form-confirm_return_waybill').submit();
        }
      }
    );
  });
});
            </script>
          {% endblock %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/waybill/detail_waybill.html
{% extends "wuliu/waybill/_layout_edit_waybill.html" %}
{% load show_waybill_routing_operation_info from wuliu_extras %}
{% block title %}运单详情{% endblock %}
{% block header_title %}运单详情{% endblock %}
              {% block content_header %}
                <div class="col"><div class="card card-primary card-tabs">
                  {% if wb.status == WB_STATUSES.SignedFor %}
                    <div class="ribbon-wrapper ribbon-xl">
                        <div class="ribbon bg-success text-xl">已签收</div>
                    </div>
                  {% elif wb.status == WB_STATUSES.Returned %}
                    <div class="ribbon-wrapper ribbon-xl">
                        <div class="ribbon bg-warning text-xl">已退货</div>
                    </div>
                  {% elif wb.status == WB_STATUSES.Dropped %}
                    <div class="ribbon-wrapper ribbon-xl">
                        <div class="ribbon bg-danger text-xl">已作废</div>
                    </div>
                  {% endif %}
                    <div class="card-header p-0 pt-1">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="tabs-waybill-info-tab" data-toggle="pill" href="#tabs-waybill-info" role="tab" aria-controls="tabs-waybill-info" aria-selected="true">运单信息</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="tabs-waybill-routing-tab" data-toggle="pill" href="#tabs-waybill-routing" role="tab" aria-controls="tabs-waybill-routing" aria-selected="false">运单路由</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="tabs-waybill-cargo-price-tab" data-toggle="pill" href="#tabs-waybill-cargo-price" role="tab" aria-controls="tabs-waybill-cargo-price" aria-selected="false">代收款状态</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content" id="custom-tabs-one-tabContent">
                            <div class="tab-pane fade show active" id="tabs-waybill-info" role="tabpanel" aria-labelledby="tabs-waybill-info-tab">
              {% endblock %}
              {# 此处为运单详情 #}
              {% block content_footer %}
                            </div>
                            <div class="tab-pane fade" id="tabs-waybill-routing" role="tabpanel" aria-labelledby="tabs-waybill-routing-tab">
                                <div class="table-responsive" style="border: 1px solid #bbb; height: 400px;">
                                    <table class="table table-bordered table-hover">
                                        <thead>
                                            <tr class="thead-light">
                                                <th>#</th>
                                                <th>操作时间</th>
                                                <th>操作类型</th>
                                                <th>操作部门</th>
                                                <th>操作用户</th>
                                                <th>详细内容</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                          {% for rt in wb_routing %}
                                            <tr>
                                                <th>{{ forloop.counter }}</th>
                                                <td>{{ rt.time | date:"Y-m-d H:i:s" }}</td>
                                                <td>{{ rt.get_operation_type_display }}</td>
                                                <td>{{ rt.operation_dept.name }}</td>
                                                <td>{{ rt.operation_user.name }}</td>
                                                <td>{% show_waybill_routing_operation_info rt %}</td>
                                            </tr>
                                          {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tabs-waybill-cargo-price" role="tabpanel" aria-labelledby="tabs-waybill-cargo-price-tab">
                              {% if wb.cargo_price > 0 %}
                                <blockquote>
                                    <h1>代收款信息</h1>
                                    <p>
                                        代收货款：<code>{{ wb.cargo_price }}</code>元；
                                        扣付运费：<code>{% if wb.fee_type == WB_FEE_TYPES.Deduction %}{{ wb.fee }}{% else %}0{% endif %}</code>元；
                                        扣除手续费：<code>{{ wb.cargo_handling_fee }}</code>元；
                                        实际领款：<code>{{ wb_final_cpp_fee }}</code>元。
                                    </p>
                                </blockquote>
                                <blockquote>
                                    <h1>代收款当前状态：{{ wb.get_cargo_price_status_display }}</h1>
                                    <p>
                                    {% with wb_cpp=wb.cargo_price_payment %}
                                      {% if wb_cpp %}
                                          <a href="{% url 'wuliu:detail_cargo_price_payment' wb_cpp.id %}">代收款转账单</a>
                                        {% if wb_cpp.status == CPP_STATUSES.Created %}已由{{ wb_cpp.create_user.name }}创建，尚未提交。
                                        {% elif wb_cpp.status == CPP_STATUSES.Submitted %}已由{{ wb_cpp.create_user.name }}创建并提交财务部，等待审核。
                                        {% elif wb_cpp.status == CPP_STATUSES.Reviewed %}已由财务部审核完毕。
                                        {% elif wb_cpp.status == CPP_STATUSES.Paid %}已由财务部完成支付，结算时间：{{ wb_cpp.settle_accounts_time | date:"Y年n月j日 H:i:s" }}。
                                        {% elif wb_cpp.status == CPP_STATUSES.Rejected %}已被财务部驳回。
                                        {% endif %}
                                      {% else %}
                                        {% if wb.status == WB_STATUSES.SignedFor %}尚未创建代收款转账单。
                                        {% else %}运单没有被签收，不能创建代收款转账单。
                                        {% endif %}
                                      {% endif %}
                                    {% endwith %}
                                    </p>
                                </blockquote>
                              {% else %}
                                <blockquote>
                                    <h1>代收款当前状态：{{ wb.get_cargo_price_status_display }}</h1>
                                    <p>该运单没有代收货款。</p>
                                </blockquote>
                              {% endif %}
                            </div>
                        </div>
                    </div>
                </div></div>
                <script>
$(function() {
    $(".container-fluid > .card").removeClass("card").removeClass("p-3");
    $(".ribbon-wrapper").click(function(){$(this).slideUp()});
});
                </script>
              {% endblock %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/waybill/edit_waybill.html
{% extends "wuliu/waybill/_layout_edit_waybill.html" %}
{% block title %}运单修改{% endblock %}
{% block header_title %}运单修改{% endblock %}
{% block edit_form_action %}{% url 'wuliu:edit_waybill' %}{% endblock %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/waybill/manage_waybill.html
{% extends "wuliu/waybill/_layout_search_waybill.html" %}
{% load wuliu_extras %}
{% block title %}运单管理{% endblock %}
{% block header_title %}运单管理{% endblock %}
{% block header_subtitle %}查询、修改、作废或补打运单{% endblock %}
{% block head_append_js %}
  <script src="{% url 'wuliu:manage_waybill_js' %}"></script>
{% endblock %}
              {% block search_form_action %}{% url 'wuliu:manage_waybill' %}{% endblock %}
              {% block action_bar %}
                <form id="form-create_transport_out" action="{% url 'wuliu:add_waybills_to_transport_out' %}" method="post" hidden>
                    {% csrf_token %}
                    <input type="text" name="wb_add_list">
                </form>
              {% if "manage_waybill__edit_delete_print"|is_logged_user_has_perm:request %}
                <button class="btn btn-outline-primary btn-sm" id="button_wb_edit">
                    <i class="ri-c ri-file-edit-line"><span>修改</span></i>
                </button>
                <button class="btn btn-outline-primary btn-sm" id="button_wb_drop">
                    <i class="ri-c ri-delete-bin-line"><span>删除</span></i>
                </button>
                <button class="btn btn-outline-primary btn-sm" id="button_wb_print">
                    <i class="ri-c ri-printer-line"><span>补打</span></i>
                </button>
              {% endif %}
              {% if "manage_transport_out__add_edit_delete_start"|is_logged_user_has_perm:request %}
                <button class="btn btn-outline-primary btn-sm" id="button_wb_create_transport_out">
                    <i class="ri-c ri-truck-line"><span>添加并创建车次</span></i>
                </button>
              {% endif %}
              {% endblock %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/waybill/quick_search_waybill.html
{% extends "wuliu/_layout.html" %}
{% load wuliu_extras %}
{% block title %}查询结果{% endblock %}
{% block header_title %}查询结果{% endblock %}
              {% block content %}
                {% show_waybill_table waybill_list "quick_search_waybill_result" False %}
                <!-- 移除最外层的card边框 -->
                <script>$(function() {$(".container-fluid > .card").removeClass("card").removeClass("p-3");});</script>
              {% endblock %}