python/projects/Django_Transportation_Management_System-main/PPWuLiu/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', RedirectView.as_view(url='tms/login')),
    path('tms/', include('wuliu.urls')),
    path('utils/', include('utils.urls')),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

python/projects/Django_Transportation_Management_System-main/utils/urls.py
from django.urls import path

from . import views

app_name = "utils"
urlpatterns = [
    path("export_excel", views.export_excel, name="export_excel"),
]

python/projects/Django_Transportation_Management_System-main/wuliu/urls.py
from django.urls import path, include

from . import views, apis

# Unused
def easy_path(view_func):
    """ 只需给定视图函数, route和name都设置为视图函数的名字 """
    return path(view_func.__name__, view_func, name=view_func.__name__)

app_name = "wuliu"
urlpatterns = [
    # 登录
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("change_password", views.change_password, name="change_password"),
    path("", views.welcome, name="welcome"),
    path("welcome_action.js", views.welcome_js, name="welcome_js"),
    # 系统设置
    path("settings/", include([
        path("manage_users", views.manage_users, name="manage_users"),
        path("add_user", views.add_user, name="add_user"),
        path("manage_user_permission", views.manage_user_permission, name="manage_user_permission"),
        path("batch_edit_user_permission", views.batch_edit_user_permission, name="batch_edit_user_permission"),
    ])),
    # 运单管理
    path("waybill/", include([
        path("add", views.add_waybill, name="add_waybill"),
        path("edit", views.edit_waybill, name="edit_waybill"),
        path("edit.js", views.edit_waybill_js, name="edit_waybill_js"),
        path("manage", views.ManageWaybill.as_view(), name="manage_waybill"),
        path("manage.js", views.manage_waybill_js, name="manage_waybill_js"),
        path("detail/<int:waybill_id>", views.detail_waybill, name="detail_waybill"),
        path("quick_search", views.quick_search_waybill, name="quick_search_waybill"),
        path("confirm_return", views.confirm_return_waybill, name="confirm_return_waybill"),
    ])),
    # 发车管理
    path("transport_out/", include([
        path("add", views.add_transport_out, name="add_transport_out"),
        path("edit", views.edit_transport_out, name="edit_transport_out"),
        path("edit.js", views.edit_transport_out_js, name="edit_transport_out_js"),
        path("manage", views.manage_transport_out, name="manage_transport_out"),
        path("manage.js", views.manage_transport_out_js, name="manage_transport_out_js"),
        path("detail", views.detail_transport_out, name="detail_transport_out"),
        path("search_waybills", views.SearchWaybillsToTransportOut.as_view(), name="search_waybills_to_transport_out"),
        path("add_waybills", views.add_waybills_to_transport_out, name="add_waybills_to_transport_out"),
    ])),
    # 到货管理
    path("arrival/", include([
        path("manage", views.manage_arrival, name="manage_arrival"),
        path("confirm", views.confirm_arrival, name="confirm_arrival"),
    ])),
    # 客户签收
    path("sign_for/", include([
        path("manage", views.ManageSignFor.as_view(), name="manage_sign_for"),
        path("confirm", views.confirm_sign_for, name="confirm_sign_for"),
        path("confirm.js", views.confirm_sign_for_js, name="confirm_sign_for_js"),
    ])),
    # 财务管理
    path("finance/", include([
        path("department_payment/", include([
            path("add", views.add_department_payment, name="add_department_payment"),
            path("manage", views.manage_department_payment, name="manage_department_payment"),
            path("manage.js", views.manage_department_payment_js, name="manage_department_payment_js"),
            path("detail/<int:dp_id>", views.detail_department_payment, name="detail_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("add", views.add_cargo_price_payment, name="add_cargo_price_payment"),
            path("edit", views.edit_cargo_price_payment, name="edit_cargo_price_payment"),
            path("edit.js", views.edit_cargo_price_payment_js, name="edit_cargo_price_payment_js"),
            path("detail/<int:cpp_id>", views.detail_cargo_price_payment, name="detail_cargo_price_payment"),
            path("manage", views.manage_cargo_price_payment, name="manage_cargo_price_payment"),
            path("manage.js", views.manage_cargo_price_payment_js, name="manage_cargo_price_payment_js"),
        ])),
        path("customer_score_log/", include([
            path("manage", views.manage_customer_score, name="manage_customer_score"),
            path("add", views.add_customer_score_log, name="add_customer_score_log"),
        ])),
    ])),
    # 业务报表
    path("report_table/", include([
        path("src_waybill", views.ReportTableSrcWaybill.as_view(), name="report_table_src_waybill"),
        path("stock_waybill", views.ReportTableStockWaybill.as_view(), name="report_table_stock_waybill"),
        path("dst_waybill", views.ReportTableDstWaybill.as_view(), name="report_table_dst_waybill"),
        path("dst_stock_waybill", views.ReportTableDstStockWaybill.as_view(), name="report_table_dst_stock_waybill"),
        path("sign_for_waybill", views.ReportTableSignForWaybill.as_view(), name="report_table_sign_for_waybill"),
    ])),
    # apis
    path("api/", include([
        path("gen_standard_fee", apis.gen_standard_fee, name="api_gen_standard_fee"),
        path("check_old_password", apis.check_old_password, name="api_check_old_password"),
        # 用以获取模型对象属性的api
        path("get/", include([
            path("customer_info", apis.get_customer_info, name="api_get_customer_info"),
            path("department_info", apis.get_department_info, name="api_get_department_info"),
            path("waybills_info", apis.get_waybills_info, name="api_get_waybills_info"),
            path("truck_info", apis.get_truck_info, name="api_get_truck_info"),
            path("user_info", apis.get_user_info, name="api_get_user_info"),
            path("user_permission", apis.get_user_permission, name="api_get_user_permission"),
        ])),
        # 用以操作模型和会话的api
        path("remove_waybill_when_add_transport_out", apis.remove_waybill_when_add_transport_out,
             name="api_remove_waybill_when_add_transport_out"),
        path("remove_waybill_when_edit_transport_out", apis.remove_waybill_when_edit_transport_out,
             name="api_remove_waybill_when_edit_transport_out"),
        path("add_waybill_when_confirm_sign_for", apis.add_waybill_when_confirm_sign_for,
             name="api_add_waybill_when_confirm_sign_for"),
        path("add_waybill_when_edit_cargo_price_payment", apis.add_waybill_when_edit_cargo_price_payment,
             name="api_add_waybill_when_edit_cargo_price_payment"),
        path("drop_waybill", apis.DropWaybill.as_view(), name="api_drop_waybill"),
        path("drop_transport_out", apis.DropTransportOut.as_view(), name="api_drop_transport_out"),
        path("start_transport_out", apis.StartTransportOut.as_view(), name="api_start_transport_out"),
        path("confirm_arrival", apis.ConfirmArrival.as_view(), name="api_confirm_arrival"),
        path("confirm_sign_for", apis.ConfirmSignFor.as_view(), name="api_confirm_sign_for"),
        path("department_payment/", include([
            path("modify_remark", apis.ModifyRemarkDepartmentPayment.as_view(),
                 name="api_modify_remark_department_payment"),
            path("drop", apis.DropDepartmentPayment.as_view(),
                 name="api_drop_department_payment"),
            path("review", apis.ConfirmReviewDepartmentPayment.as_view(),
                 name="api_review_department_payment"),
            path("pay", apis.ConfirmPayDepartmentPayment.as_view(),
                 name="api_pay_department_payment"),
            path("settle_accounts", apis.ConfirmSettleAccountsDepartmentPayment.as_view(),
                 name="api_settle_accounts_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("drop", apis.DropCargoPricePayment.as_view(),
                 name="api_drop_cargo_price_payment"),
            path("submit", apis.ConfirmSubmitCargoPricePayment.as_view(),
                 name="api_submit_cargo_price_payment"),
            path("review", apis.ConfirmReviewCargoPricePayment.as_view(),
                 name="api_review_cargo_price_payment"),
            path("reject", apis.ConfirmRejectCargoPricePayment.as_view(),
                 name="api_reject_cargo_price_payment"),
            path("pay", apis.ConfirmPayCargoPricePayment.as_view(),
                 name="api_pay_cargo_price_payment"),
        ])),
    ])),
]

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/_inclusions/_tables/_cargo_price_payment_table.html
{% load wuliu_extras %}
{% load subtract from utils_extras %}
<div class="card card-primary card-outline shadow"><div class="card-body">
    <table id="{{ table_id }}" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>
                    <div class="custom-control custom-checkbox ml-2">
                        <input type="checkbox" class="custom-control-input" id="{{ table_id }}_checkbox_all">
                        <label class="custom-control-label" for="{{ table_id }}_checkbox_all"></label>
                    </div>
                </th>
                <th>账单编号</th>
                <th>状态</th>
                <th>创建时间</th>
                <th>结算时间</th>
                <th>创建人</th>
                <th>收款人姓名</th>
                <th>收款人电话号码</th>
                <th>收款人银行名称</th>
                <th>收款人银行卡号</th>
                <th>收款人身份证号</th>
                <th>应付货款</th>
                <th>扣付运费</th>
                <th>手续费</th>
                <th>实付金额</th>
                <th>备注</th>
            </tr>
        </thead>
        <tbody>
          {% for cargo_price_payment in cargo_price_payment_list %}
            <tr>
                <td></td>
                <td data-cpp_id="{{ cargo_price_payment.id }}">
                    <div class="custom-control custom-checkbox ml-2">
                        <input type="checkbox" class="custom-control-input" id="{{ table_id }}_to_{{ cargo_price_payment.id }}">
                        <label class="custom-control-label" for="{{ table_id }}_to_{{ cargo_price_payment.id }}"></label>
                    </div>
                </td>
                <td data-order="{{ cargo_price_payment.id }}"><a href="{% url 'wuliu:detail_cargo_price_payment' cargo_price_payment.id %}">{{ cargo_price_payment.get_full_id }}</a></td>
                <td data-key="cpp_status" data-status_id="{{ cargo_price_payment.status }}" data-order="{{ cargo_price_payment.status }}">{{ cargo_price_payment.get_status_display }}</td>
                <td data-key="cpp_create_time" data-order="{{ cargo_price_payment.create_time.timestamp }}">{{ cargo_price_payment.create_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="cpp_settle_accounts_time" data-order="{{ cargo_price_payment.settle_accounts_time.timestamp }}">{{ cargo_price_payment.settle_accounts_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="cpp_create_user" data-user_id="{{ cargo_price_payment.create_user.id }}">{{ cargo_price_payment.create_user.name }}</td>
                <td data-key="cpp_payee_name">{{ cargo_price_payment.payee_name }}</td>
                <td data-key="cpp_payee_phone">{{ cargo_price_payment.payee_phone }}</td>
                <td data-key="cpp_payee_bank_name">{{ cargo_price_payment.payee_bank_name }}</td>
                <td data-key="cpp_payee_bank_number">{{ cargo_price_payment.payee_bank_number }}</td>
                <td data-key="cpp_payee_credential_num">{{ cargo_price_payment.payee_credential_num }}</td>
              {% with total_fee=cargo_price_payment.gen_total_fee %}
                <td data-key="cpp_total_cargo_price">{{ total_fee.cargo_price }}</td>
                <td data-key="cpp_total_deduction_fee">{{ total_fee.deduction_fee }}</td>
                <td data-key="cpp_total_deduction_fee">{{ total_fee.cargo_handling_fee }}</td>
                <td data-key="cpp_final_fee">{{ total_fee.cargo_price | subtract:total_fee.deduction_fee | subtract:total_fee.cargo_handling_fee }}</td>
              {% endwith %}
                <td data-key="cpp_remark">{{ cargo_price_payment.remark }}</td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
</div></div>
{% js_init_datatable table_id True 4 %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/_inclusions/_tables/_customer_score_log_table.html
{% load wuliu_extras %}
{% load bool from utils_extras %}
<div class="card card-primary card-outline shadow"><div class="card-body">
    <table id="{{ table_id }}" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>会员姓名</th>
                <th>会员电话</th>
                <th>变动方式</th>
                <th>变动积分</th>
                <th>变动时间</th>
                <th>操作人</th>
                <th>变更原因</th>
                <th>关联运单</th>
            </tr>
        </thead>
        <tbody>
          {% for customer_score_log in customer_score_logs %}
            <tr>
                <td></td>
                <td>
                    <a href="javascript: show_customer_score({{ customer_score_log.customer.id }})">{{ customer_score_log.customer.name }}</a>
                </td>
                <td>{{ customer_score_log.customer.phone }}</td>
                <td data-inc_or_dec="{{ customer_score_log.inc_or_dec | bool }}">{% if customer_score_log.inc_or_dec %}增加{% else %}扣减{% endif %}</td>
                <td data-order="{{ customer_score_log.score }}">{{ customer_score_log.score }}</td>
                <td data-order="{{ customer_score_log.create_time.timestamp }}">{{ customer_score_log.create_time | date:"Y-m-d H:i:s" }}</td>
                <td>{% if customer_score_log.user %}{{ customer_score_log.user.name }}{% else %}<span style="font-style: italic">系统自动生成</span>{% endif %}</td>
                <td>{{ customer_score_log.remark }}</td>
                <td>
                  {% if customer_score_log.waybill %}
                    <a href="{% url 'wuliu:detail_waybill' customer_score_log.waybill.id %}">{{ customer_score_log.waybill.get_full_id }}</a>
                  {% endif %}
                </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
</div></div>
{% js_init_datatable table_id False %}
<script>
  function show_customer_score(customer_id) {
    $.ajax({
      url: "{% url 'wuliu:api_get_customer_info' %}?customer_id=" + customer_id,
      type: "GET",
      async: false,
      dataType: "json",
      success: function(data, status) {
        new duDialog(
          "客户：" + data.data.customer_info.name,
          "当前积分：" + data.data.customer_info.score,
          {okText: "确认"}
        );
      },
    });
  }
</script>

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/_inclusions/_tables/_department_payment_table.html
{% load wuliu_extras %}
{% load sum from utils_extras %}
<div class="card card-primary card-outline shadow"><div class="card-body">
    <table id="{{ table_id }}" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>
                    <div class="custom-control custom-checkbox ml-2">
                        <input type="checkbox" class="custom-control-input" id="{{ table_id }}_checkbox_all">
                        <label class="custom-control-label" for="{{ table_id }}_checkbox_all"></label>
                    </div>
                </th>
                <th>账单编号</th>
                <th>状态</th>
                <th>应回款日期</th>
                <th>创建时间</th>
                <th>结算时间</th>
                <th>回款部门</th>
                <th>收款部门</th>
                <th>应回款金额总计</th>
                <th>现付运费合计</th>
                <th>提付运费合计</th>
                <th>代收货款合计</th>
                <th hidden>回款部门备注</th>
                <th hidden>收款部门备注</th>
            </tr>
        </thead>
        <tbody>
          {% for department_payment in department_payment_list %}
            <tr>
                <td></td>
                <td data-dp_id="{{ department_payment.id }}">
                    <div class="custom-control custom-checkbox ml-2">
                        <input type="checkbox" class="custom-control-input" id="{{ table_id }}_to_{{ department_payment.id }}">
                        <label class="custom-control-label" for="{{ table_id }}_to_{{ department_payment.id }}"></label>
                    </div>
                </td>
                <td data-order="{{ department_payment.id }}"><a href="{% url 'wuliu:detail_department_payment' department_payment.id %}">{{ department_payment.get_full_id }}</a></td>
                <td data-key="dp_status" data-status_id="{{ department_payment.status }}" data-order="{{ department_payment.status }}">{{ department_payment.get_status_display }}</td>
                <td data-key="dp_payment_date">{{ department_payment.payment_date | date:"Y-m-d" }}</td>
                <td data-key="dp_create_time" data-order="{{ department_payment.create_time.timestamp }}">{{ department_payment.create_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="dp_settle_accounts_time" data-order="{{ department_payment.settle_accounts_time.timestamp }}">{{ department_payment.settle_accounts_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="dp_src_department" data-src_dept_id="{{ department_payment.src_department.id }}">{{ department_payment.src_department.name }}</td>
                <td data-key="dp_dst_department" data-dst_dept_id="{{ department_payment.dst_department.id }}">{{ department_payment.dst_department.name }}</td>
              {% with total_fee_dic=department_payment.gen_total_fee %}
                <td data-key="dp_final_total_fee">{{ total_fee_dic.values | sum }}</td>
                <td data-key="dp_total_fee_now">{{ total_fee_dic.fee_now }}</td>
                <td data-key="dp_total_fee_sign_for">{{ total_fee_dic.fee_sign_for }}</td>
                <td data-key="dp_total_cargo_price">{{ total_fee_dic.cargo_price }}</td>
              {% endwith %}
                <td hidden data-key="dp_src_remark">{{ department_payment.src_remark }}</td>
                <td hidden data-key="dp_dst_remark">{{ department_payment.dst_remark }}</td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
</div></div>
{% js_init_datatable table_id True 4 %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/_inclusions/_tables/_dst_stock_waybill_table.html
{% load wuliu_extras %}
<div class="card card-primary card-outline shadow"><div class="card-body">
    <table id="{{ table_id }}" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>运单号码</th>
                <th>开票日期</th>
                <th>到货日期</th>
                <th>滞留天数</th>
                <th>发货部门</th>
                <th>到达部门</th>
                <th>发货人</th>
                <th>发货人电话</th>
                <th>收货人</th>
                <th>收货人电话</th>
                <th>货物名称</th>
                <th>件数</th>
                <th>体积</th>
                <th>重量</th>
                <th>代收货款</th>
                <th>运费</th>
                <th>结算方式</th>
            </tr>
        </thead>
        <tbody>
          {% for waybill in waybills_info_list %}
            <tr>
                <td></td>
                <td data-order="{{ waybill.id }}"><a href="{% url 'wuliu:detail_waybill' waybill.id %}">{{ waybill.get_full_id }}</a></td>
                <td data-key="wb_create_time" data-order="{{ waybill.create_time.timestamp }}">{{ waybill.create_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="wb_arrival_time" data-order="{{ waybill.arrival_time.timestamp }}">{{ waybill.arrival_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="wb_stay_days" data-order="{{ waybill.stay_days }}">{{ waybill.stay_days }}</td>
                <td data-key="wb_src_department" data-src_dept_id="{{ waybill.src_department.id }}">{{ waybill.src_department.name }}</td>
                <td data-key="wb_dst_department" data-dst_dept_id="{{ waybill.dst_department.id }}">{{ waybill.dst_department.name }}</td>
                <td data-key="wb_src_customer_name">{{ waybill.src_customer_name }}</td>
                <td data-key="wb_dst_customer_name">{{ waybill.src_customer_phone }}</td>
                <td data-key="wb_dst_customer_name">{{ waybill.dst_customer_name }}</td>
                <td data-key="wb_dst_customer_phone">{{ waybill.dst_customer_phone }}</td>
                <td data-key="wb_cargo_name">{{ waybill.cargo_name }}</td>
                <td data-key="wb_cargo_num">{{ waybill.cargo_num }}</td>
                <td data-key="wb_cargo_volume">{{ waybill.cargo_volume | floatformat:2 }}</td>
                <td data-key="wb_cargo_weight">{{ waybill.cargo_weight | floatformat }}</td>
                <td data-key="wb_cargo_price">{{ waybill.cargo_price }}</td>
                <td data-key="wb_fee">{{ waybill.fee }}</td>
                <td data-key="wb_fee_type" data-fee_type_id="{{ waybill.fee_type }}">{{ waybill.get_fee_type_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
</div></div>
{% js_init_datatable table_id False %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/_inclusions/_tables/_stock_waybill_table.html
{% load wuliu_extras %}
<div class="card card-primary card-outline shadow"><div class="card-body">
    <table id="{{ table_id }}" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>运单号码</th>
                <th>运单状态</th>
                <th>开票日期</th>
                <th>开票部门</th>
                <th>到达部门</th>
                <th>运费</th>
                <th>开票部门发车时间</th>
                <th>货场入库时间</th>
                <th>货场发车时间</th>
                <th>到货时间</th>
            </tr>
        </thead>
        <tbody>
          {% for waybill in waybills_info_list %}
            <tr>
                <td></td>
                <td data-order="{{ waybill.id }}"><a href="{% url 'wuliu:detail_waybill' waybill.id %}">{{ waybill.get_full_id }}</a></td>
                <td data-key="wb_status" data-order="{{ waybill.status }}" data-status_id="{{ waybill.status }}">{{ waybill.get_status_display }}</td>
                <td data-key="wb_create_time" data-order="{{ waybill.create_time.timestamp }}">{{ waybill.create_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="wb_src_department" data-src_dept_id="{{ waybill.src_department.id }}">{{ waybill.src_department.name }}</td>
                <td data-key="wb_dst_department" data-dst_dept_id="{{ waybill.dst_department.id }}">{{ waybill.dst_department.name }}</td>
                <td data-key="wb_fee">{{ waybill.fee }}</td>
                <td data-key="wb_departed_time" data-order="{{ waybill.departed_time.timestamp }}">{{ waybill.departed_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="wb_goods_yard_arrived_time" data-order="{{ waybill.goods_yard_arrived_time.timestamp }}">{{ waybill.goods_yard_arrived_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="wb_goods_yard_departed_time" data-order="{{ waybill.goods_yard_departed_time.timestamp }}">{{ waybill.goods_yard_departed_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="wb_arrival_time" data-order="{{ waybill.arrival_time.timestamp }}">{{ waybill.arrival_time | date:"Y-m-d H:i:s" }}</td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
</div></div>
{% js_init_datatable table_id False 3 %}

python/projects/Django_Transportation_Management_System-main/wuliu/templates/wuliu/_inclusions/_tables/_transport_out_table.html
{% load wuliu_extras %}
<div class="card card-primary card-outline shadow"><div class="card-body">
    <table id="{{ table_id }}" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>
                    <div class="custom-control custom-checkbox ml-2">
                        <input type="checkbox" class="custom-control-input" id="{{ table_id }}_checkbox_all">
                        <label class="custom-control-label" for="{{ table_id }}_checkbox_all"></label>
                    </div>
                </th>
                <th>车次编号</th>
                <th>车次状态</th>
                <th>创建时间</th>
                <th>发车时间</th>
                <th>到达时间</th>
                <th>发车部门</th>
                <th>到达部门</th>
                <th>车牌号</th>
                <th>驾驶员</th>
                <th>驾驶员电话</th>
                <th>货物总单数</th>
                <th>货物总件数</th>
                <th>货物总体积 (m³)</th>
                <th>货物总重量 (Kg)</th>
            </tr>
        </thead>
        <tbody>
          {% for transport_out in transport_out_list %}
            <tr>
                <td></td>
                <td data-to_id="{{ transport_out.id }}">
                    <div class="custom-control custom-checkbox ml-2">
                        <input type="checkbox" class="custom-control-input" id="{{ table_id }}_to_{{ transport_out.id }}">
                        <label class="custom-control-label" for="{{ table_id }}_to_{{ transport_out.id }}"></label>
                    </div>
                </td>
                <td data-order="{{ transport_out.id }}"><a href="{% url 'wuliu:detail_transport_out' %}?transport_out_id={{ transport_out.id }}">{{ transport_out.get_full_id }}</a></td>
                <td data-key="to_status" data-order="{{ transport_out.status }}" data-status_id="{{ transport_out.status }}">{{ transport_out.get_status_display }}</td>
                <td data-key="to_create_time" data-order="{{ transport_out.create_time.timestamp }}">{{ transport_out.create_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="to_start_time" data-order="{{ transport_out.start_time.timestamp }}">{{ transport_out.start_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="to_end_time" data-order="{{ transport_out.end_time.timestamp }}">{{ transport_out.end_time | date:"Y-m-d H:i:s" }}</td>
                <td data-key="to_src_department" data-src_dept_id="{{ transport_out.src_department.id }}">{{ transport_out.src_department.name }}</td>
                <td data-key="to_dst_department" data-dst_dept_id="{{ transport_out.dst_department.id }}">{{ transport_out.dst_department.name }}</td>
                <td data-key="to_truck" data-truck_id="{{ transport_out.truck.id }}">{{ transport_out.truck.number_plate }}</td>
                <td data-key="to_driver_name">{{ transport_out.driver_name }}</td>
                <td data-key="to_driver_phone">{{ transport_out.driver_phone }}</td>
                <td data-key="to_total_num">{{ transport_out.total_num }}</td>
                <td data-key="to_total_cargo_num">{{ transport_out.total_cargo_num }}</td>
                <td data-key="to_total_cargo_volume">{{ transport_out.total_cargo_volume | floatformat:2 }}</td>
                <td data-key="to_total_cargo_weight">{{ transport_out.total_cargo_weight | floatformat }}</td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
</div></div>
{% js_init_datatable table_id True 4 %}